version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: LaOne
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    expose:
      - 6379
  celery_worker:
    build: .
    container_name: celery_worker
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command: celery worker -B -A worker_celery -l info --pool=solo

  bot:
    build: .
    container_name: bot
    env_file:
      - .env
    command: python main.py
    depends_on:
      - db
